### ISSUE TITLE
Rogue console.log statement

### ISSUE THREAD

**Issue by mrkrstphr** [ryanjyost/react-simple-storage#14]
Maybe you're just trying to give a gentle reminder to everyone to test their code?

https://github.com/ryanjyost/react-simple-storage/blob/c0412962b473fa977cdc1ff7835fe975e08ec7df/build/index.js#L268

**Comment by ryanjyost** [comment]
No, I just f'ed up while hastily fixing a bad merge earlier this week. There's already a PR to fix, I just gotta check it out and merge tonight.

Thanks!

**Comment by ryanjyost** [comment]
All fixed with @nicolasbettag 's PR and v1.4.0 now published on npm.

Thanks folks
