### ISSUE TITLE
react should not be part of dependencies

### ISSUE THREAD

**Issue by Nouzbe** [ryanjyost/react-simple-storage#16]
`react-simple-storage` requires `react` as `peer-dependency` but also as `dependency`.

This is a problem because it leads projects using `react-simple-storage` to end up with multiple instances or `react` (at least when these projects don't precisely use `react@16.5.4`).

I believe that `react` should be removed from the `dependencies` (and moved to `devDependencies` if it is required during development). Also, even if the version of the devDependency remains `^16.5.4` as it currently is, it would be nicer for the peerDependency's version to be more flexible (`^16.0.0` for example)

Not as problematic, but on a related note: `webpack` could probably be moved to `devDependencies` too.

**Comment by ryanjyost** [comment]
Those are great points @Nouzbe, this is definitely something worth fixing. 

I'll learn a bit more about dependencies and make the optimizations you suggest plus any others I find.

**Comment by ryanjyost** [comment]
Resolved with latest PR, thanks @Nouzbe https://github.com/ryanjyost/react-simple-storage/pull/17
