### ISSUE TITLE
No "parent" prop was provided to react-simple-storage. 

### ISSUE THREAD

**Issue by floppyspace** [ryanjyost/react-simple-storage#18]
Hi, the error seems straight forward but not sure how to fix, using hooks and as far as I can tell it should be working. I am using it in a child component as when I try to run in app.js it gives an error.

> index.js:1375 No "parent" prop was provided to react-simple-storage. A parent component's context is required in order to access and update the parent component's state.
			
Try the following: <SimpleStorage parent={this} />

I am using react-router-dom so not sure if this could be causing the issue? 

Apart from that I like what you have done here.

**Comment by ryanjyost** [comment]
Could you provide a code snippet where you're using the component that's causing issues @floppyspace ?

Seems like you didn't pass a `parent` prop to the component, which in most cases will just be `this`, which refers to the parent component. 

[Check out the docs for proper usage.](https://github.com/ryanjyost/react-simple-storage#component)

**Comment by floppyspace** [comment]
> I think the react-simple-storage component requires that the parent be a class component

This is what I came to as well, Tried as a class and it worked as intended. 

I did change it to take in the props which stopped it from throwing an error but nothing occurred in local storage, I moved on fairly quickly after this. Apologies and will take more notes in the future to be more helpful.

**Comment by ryanjyost** [comment]
Ok, I'm gonna close this out and if you have any issues next time you give it a go, please open another issue.
