### ISSUE TITLE
Not working on iphone

### ISSUE THREAD

**Issue by thebarty** [ryanjyost/react-simple-storage#2]
Hi there,

this is working fine on Desktop
BUT NOT on Iphone's Safari.

I have just tested on Chrome (OSX) and Iphone Safara so far.

Any ideas how to fix this?

Maybe use a package like this to build on https://www.npmjs.com/package/store?

**Comment by ryanjyost** [comment]
Hey @thebarty, thanks for letting me know it doesn't work on Safari mobile, definitely worth adding. 

I've never used that store library before, and looks a little unmaintained, so I'll take a stab at incorporating Cookie storage as a backup option, in case localStorage isn't available. I'll probably add sessionStorage too while I'm at it.

Thanks for the suggestion!

**Comment by thebarty** [comment]
Yeah, cool to hear that you are planning to support it.

I have not used the mentioned package myself. I read about it here https://themeteorchef.com/tutorials/building-persistent-uis-with-react-state-and-local-storage.

**Comment by thebarty** [comment]
Hi, just run into problems testing this on IE11.

Unfortunatly it does NOT seem to work on IE11.

In the IE11-Console I am getting the error ".includes-method NOT support" in this code:
```
			// loop through localStorage
			for (var key in localStorage) {
				// if the localStorage item is in the current parent's state and isn't a localStorage method
				if (key.includes(prefix) && typeof localStorage[key] !== 'function' && key !== 'length') {
					// get the property value from localStorage
					var value = localStorage.getItem(key);

					// remove the parent-specific prefix to get original key from parent's state
					var name = key.slice(prefix.length + 1);
```

**Comment by thebarty** [comment]
Ha!!

Keeping you updated...

Adding polyfills helps with the ie11 issue!!

Maybe add to the docs to also add https://babeljs.io/docs/usage/polyfill/ via
`yarn add babel-polyfill;`

and 

`import "babel-polyfill";`

Iphone still does not work

**Comment by ryanjyost** [comment]
Alrighty, thanks a ton for the help @thebarty. 

I took a closer look at store.js and found it to be a solid solution - why reinvent the wheel? So I implemented that and updated the README for the IE11 polyfill solution.

Please let me know if my changes fixed these compatibility issues, and we'll close this issue.

Again, really appreciate your help!

**Comment by thebarty** [comment]
Yeah man!!! Great job!

**Comment by ryanjyost** [comment]
Fantastic, I'll close this issue.
