### ISSUE TITLE
Error with saving an array with one integer

### ISSUE THREAD

**Issue by 1gory** [ryanjyost/react-simple-storage#20]
Hi, thanks for the lib.

When I trying to save an array with one integer value, 
it is stored not as an array:
this.setState({ test: [1]})

console.log(this.state); // { test = 1; }

**Comment by ryanjyost** [comment]
Sorry for the long response time - for some reason I get ZERO notifications for my own repo! Will look into this!

**Comment by ryanjyost** [comment]
@1gory This should be fixed with the latest release, please let me know if not!
