### ISSUE TITLE
Doesn't work with react-router

### ISSUE THREAD

**Issue by kiikoh** [ryanjyost/react-simple-storage#21]
Using <Link to="/"> doesn't trigger a page reload so the state doesn't save.

**Comment by kiikoh** [comment]
After further experimentation, it appears it actually saves, but doesn't trigger the state hydration without a full page refresh.

**Comment by ryanjyost** [comment]
Hmmmm will have to figure out why, b/c it should save/hydrate whenever the component unmounts/mounts.

Maybe your use case with react-router is too sophisticated for the `simple` in `react-simple-storage`.

Do you have a public repo I could peek at for the specific implementation? 

Thanks for pointing this out!

**Comment by kiikoh** [comment]
Sorry just seeing this now, I think the problem was indeed on "my end." (actually chartjs) I was doing some weird stuff to get around something it was doing incorrectly and once I removed that it all worked. 
Chartjs was creating circular json behind my back and modifying the state of it so when it tried to save it, it got thrown an error. I believe that is where the root of the problem actually came from.
