### ISSUE TITLE
Misunderstanding clearStorage

### ISSUE THREAD

**Issue by VeronicaDem** [ryanjyost/react-simple-storage#22]
Hi,
I have used function clearStorage as it shows in the documentation(https://www.npmjs.com/package/react-simple-storage) but I think I don`t understand how it works. When I call clearStorage, nothing happens. I think that states will be removed from storage and then React will display the last version of a component. Could you tell me what`s wrong?

**Comment by ryanjyost** [comment]
`clearStorage` doesn't do anything to React state, just clears the localStorage.

You probably want to use `resetParentState` in some way to get your desired effect. Hope that helps!
