### ISSUE TITLE
Prefix stopped working

### ISSUE THREAD

**Issue by thebarty** [ryanjyost/react-simple-storage#4]
Hi @ryanjyost,

just a quick one: I just noticed that "prefix" stopped working after the update… seems like you killed it in the process. Shit can happen… :-)

By the way: The best way to monitor it is in chrome dev-console > Application-Tab > Storage > Local Storage // Session Storage

**Comment by ryanjyost** [comment]
Closing this issue due to lack of response and inability to reproduce.

If anyone's still having this issue, please let me know!
