### ISSUE TITLE
try = catch

### ISSUE THREAD

**Issue by francois-roget** [ryanjyost/react-simple-storage#5]
https://github.com/ryanjyost/react-simple-storage/blob/dbf11fa99637397522f28a76dc625a47f532a94e/src/index.js#L66

Here you are doing the same in the try and in the catch... 
In your medium article you talked about trying to parse the value for JSON objects but it seems you do not do it here...

**Comment by ryanjyost** [comment]
Thanks for pointing out @francois-roget.

My original version only used localStorage, like in the tutorial, where using JSON.parse() with the try/catch is necessary.

But as a result of [this issue](https://github.com/ryanjyost/react-simple-storage/issues/2), I opted to use [store.js](https://github.com/marcuswestin/store.js/), which handles the parsing and tons of other web storage options. So the try/catch became unnecessary.

You're 100% spot on that my code was repetitive/wrong/confusing, so I added a quick comment about store.js handling the parsing for us, and decided to keep the try/catch as an extra layer of protection, though I'm not sure if other issues could arise from that decision.

All should be good with my most recently-pushed v1.1.1, but let me know if I screwed something up in the process with another issue, thanks!
