### ISSUE TITLE
Read saved state in componentDidMount

### ISSUE THREAD

**Issue by Hurtak** [ryanjyost/react-simple-storage#6]
I have api call and the result I saved into component state.
This api call I want to have cached in localStorage and then reused on each page render.

So what I did before using this package was that in componentDidMount I checked the localStorage, if it was empty I made api call, otherwise I used data from localStorage.

Problem with this package is that componentDidMount is called before react-simple-storage populates the state of the component.

What is recommended solution to this? Maybe adding some callback would solve this?

```js
<SimpleStorage parent={this} onParentStatePopulated={this.someCallback}>
```

**Comment by ryanjyost** [comment]
Hey @Hurtak I found some time to implement a callback, `onParentStateHydrated`.

Please update and let me know if that does the trick.

**Comment by Hurtak** [comment]
Hi.

Thanks for very quick updates.
Briefly looking at the code it seems that it shod solve this issue. ATM I am at vacation so I won't be able to test this for next week or two, but after that I will let you know.

**Comment by Hurtak** [comment]
Hi, I just tested it and it seems to solve this issue. Thanks, closing this now.
