### ISSUE TITLE
Clearing the storage

### ISSUE THREAD

**Issue by Hurtak** [ryanjyost/react-simple-storage#9]
Hi,

I have few questions about clearing the storage. My usecase was that I wanted to clear the local storage and I wanted to keep it clear (so after the page reload the app starts from "unsaved" state). I lookedup the docs and there is clearStorage method that does indeed clear the relevant items in localstorage, but it seems that react-simple-storage saves state to localStorage when user reloads/leaves page so for my usecase of clearing of localStorage and keeping it clear after page reload did not work. 

This leads me to first question, shouldn't the library stop saving the state after clearStorage is called? Or perhaps start saving again only after the state changed? Or maybe adding some other method that  stops auto saving? (just throwing some ideas without really thinking them through that much). I sometimes got in state of the app where I corrupted saved storage, and because of auto syncing of state and storage my app broke and there wasn't really oneliner (like window.localStorage.clear()) way to clear the storage, it kept getting repopulated.

Second question is regarding the resetParentState method, from the docs it is not really clear what is the difference between

```js
resetParentState(this, initialState);
```

and

```js
this.setState(initialState);
```

**Comment by ryanjyost** [comment]
Hey @Hurtak , sorry for the delay, I've got an OK solution, where I set a localStorage item `didClearStorage` to `true` if the user used the helper function `clearStorage`.  If that's true, then no saving to storage takes place, and it resets to `false` in the next user session.

I will also add a simple bool prop to restrict saving to web storage.

Do you think the combo of those two will be a solution to your problem? Thanks!

**Comment by Hurtak** [comment]
Hi, I am no longer using react-simple-storage. The problems mentioned above along with other things (onParentStateHydrated instead of componentDidMount and problems related to that) made me to rewrite the localstorage save functionality to few helper functions instead of using this library. It is little more verbose (with your library you just add component and it works) but it seemed more reliable with none of the problems I mentioned in issues. I am not saying your library is bad, just that for my use case it brought more problems than it helped.

This is the api I made

```js
const localStorageKeyPrefix = "STORAGE-";

function getPrefixedKey(key, componentId) {
  return localStorageKeyPrefix + (componentId ? componentId + "-" : "") + key;
}

export function initLocalStorage(keysToSave, componentId, state) {
  const newState = { ...state };

  for (const [key, value] of Object.entries(newState)) {
    if (!keysToSave.includes(key)) continue;

    const keyLocalStorage = getPrefixedKey(key, componentId);

    const savedItem = window.localStorage[keyLocalStorage];
    if (typeof savedItem === "string") {
      newState[key] = JSON.parse(savedItem);
    } else {
      window.localStorage[keyLocalStorage] = JSON.stringify(value);
    }
  }

  return newState;
}

export function saveToLocalStorage(keysToSave, componentId, state) {
  for (const [key, value] of Object.entries(state)) {
    if (!keysToSave.includes(key)) continue;

    const keyLocalStorage = getPrefixedKey(key, componentId);
    window.localStorage[keyLocalStorage] = JSON.stringify(value);
  }
}

export function clearLocalStorage() {
  const keysToDelete = Object.keys(window.localStorage).filter(key =>
    key.startsWith(localStorageKeyPrefix)
  );

  for (const key of keysToDelete) {
    delete window.localStorage[key];
  }
}
```

And then in you component constructor instead of 

```js
this.state = {
  a: 1
}
```

you do 

```js
this.state = initLocalStorage(["a"], "componentId", {
  a: 1
})
```

And then you decide when you want to save, so for example

```js
componentDidUpdate() {
  saveToLocalStorage(["a"], "componentId", this.state); 
}
```

This API did exactly what I needed with none of the problems, so posting the code here to maybe give some inspiration what other people did.

Also another random note, whitelisting pieces of state that you want to save seems to be better approach than blacklisting.

Is it necessary to set didClearStorage in localStorage, cant we just keep it as local variable instead of polluting localStorage. Otherwise, the proposed solutions seem good.

Cheers

**Comment by ryanjyost** [comment]
Tons of helpful info, really appreciate it. 

And totally understandable that this won't be a one-size fits all solution, what you've built looks super flexible, whereas this project's trying to stay simple and a "drop-in" component, which clearly has its issues and limitations when it comes to even moderately complex use cases.

**Comment by ryanjyost** [comment]
I'll want to fix this to keep the storage clear until after next refresh
